# Azure DevOps Pipeline for Java Maven Selenium Project
trigger:
  - main
pool:
  # Specify Windows agent for the pipeline
  vmImage: 'windows-latest'
variables:
  MAVEN_OPTS: "-Xmx1024m"
steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Install JDK 21 (manual install)
- script: |
    choco install openjdk21
    java -version
  displayName: 'Install JDK 21'

# Step 3: Cache Maven packages for faster builds
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    path: '$(USERPROFILE)\.m2\repository'
    restoreKeys: |
      maven | "$(Agent.OS)"

# Step 4: Install Google Chrome and ChromeDriver for Selenium tests
- script: |
    # Install Google Chrome
    Invoke-WebRequest -Uri https://dl.google.com/chrome/install/375.126/chrome_installer.exe -OutFile chrome_installer.exe
    Start-Process -FilePath chrome_installer.exe -Args "/silent" -Wait
    Remove-Item -Force chrome_installer.exe
    "Google Chrome installed"
    
    # Install ChromeDriver
    Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip -OutFile chromedriver.zip
    Expand-Archive -Path chromedriver.zip -DestinationPath C:\chromedriver
    Remove-Item -Force chromedriver.zip
    "ChromeDriver installed"
  displayName: 'Install Chrome and ChromeDriver'

# Step 5: Build Maven project
- script: mvn clean compile
  displayName: 'Maven Clean & Compile'

# Step 6: Run Selenium tests (headless mode recommended)
- script: mvn test
  displayName: 'Run Selenium Tests'

# Step 7: Package project (optional)
- script: mvn package
  displayName: 'Maven Package'
